name: windows-latest CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, v* ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - run:  sdkmanager tools platform-tools
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - run: npm i appium@next --save-dev
      - run: npx appium driver install uiautomator2
      - run: appium server
      - run: npm install -g nightwatch@latest
      - run: npm run test:unit
